// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckGameEarlyAccess(arg1) {
  return window['go']['main']['App']['CheckGameEarlyAccess'](arg1);
}

export function CheckProfileVisibility() {
  return window['go']['main']['App']['CheckProfileVisibility']();
}

export function ClearAchievement(arg1) {
  return window['go']['main']['App']['ClearAchievement'](arg1);
}

export function ClearAllAchievements() {
  return window['go']['main']['App']['ClearAllAchievements']();
}

export function ConnectSteam() {
  return window['go']['main']['App']['ConnectSteam']();
}

export function DisconnectGame() {
  return window['go']['main']['App']['DisconnectGame']();
}

export function FetchGames() {
  return window['go']['main']['App']['FetchGames']();
}

export function FetchGlobalPercents(arg1) {
  return window['go']['main']['App']['FetchGlobalPercents'](arg1);
}

export function GetAchievementCounts() {
  return window['go']['main']['App']['GetAchievementCounts']();
}

export function GetAchievements() {
  return window['go']['main']['App']['GetAchievements']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetHLTBTimes(arg1, arg2) {
  return window['go']['main']['App']['GetHLTBTimes'](arg1, arg2);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLogContent() {
  return window['go']['main']['App']['GetLogContent']();
}

export function GetPersonaName() {
  return window['go']['main']['App']['GetPersonaName']();
}

export function GetPlaytime(arg1) {
  return window['go']['main']['App']['GetPlaytime'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToPlayList() {
  return window['go']['main']['App']['GetToPlayList']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function LoadAchievements(arg1) {
  return window['go']['main']['App']['LoadAchievements'](arg1);
}

export function LoadAchievementsFromSchema(arg1) {
  return window['go']['main']['App']['LoadAchievementsFromSchema'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function RescanAllAchievements() {
  return window['go']['main']['App']['RescanAllAchievements']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanAchievementCounts() {
  return window['go']['main']['App']['ScanAchievementCounts']();
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SetAchievement(arg1) {
  return window['go']['main']['App']['SetAchievement'](arg1);
}

export function SetAllAchievements() {
  return window['go']['main']['App']['SetAllAchievements']();
}

export function SetToPlay(arg1, arg2) {
  return window['go']['main']['App']['SetToPlay'](arg1, arg2);
}

export function StopAchievementScan() {
  return window['go']['main']['App']['StopAchievementScan']();
}

export function StoreStats() {
  return window['go']['main']['App']['StoreStats']();
}
