// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {settings} from '../models';
import {services} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckGameEarlyAccess(arg1:number):Promise<boolean>;

export function CheckProfileVisibility():Promise<string>;

export function ClearAchievement(arg1:string):Promise<boolean>;

export function ClearAllAchievements():Promise<number>;

export function ConnectSteam():Promise<number>;

export function DisconnectGame():Promise<void>;

export function FetchGames():Promise<Array<models.GameInfo>>;

export function FetchGlobalPercents(arg1:number):Promise<Record<string, number>>;

export function GetAchievementCounts():Promise<Record<number, settings.AchievementCount>>;

export function GetAchievements():Promise<Array<models.Achievement>>;

export function GetAllCachedHLTB():Promise<Record<number, settings.HLTBEntry>>;

export function GetAllPlaytimes():Promise<Record<number, number>>;

export function GetAppVersion():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetHLTBTimes(arg1:number,arg2:string):Promise<services.HLTBTimes>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLogContent():Promise<string>;

export function GetPersonaName():Promise<string>;

export function GetPlaytime(arg1:number):Promise<number>;

export function GetSettings():Promise<settings.Settings>;

export function GetToPlayList():Promise<Array<number>>;

export function IsConnected():Promise<boolean>;

export function LoadAchievements(arg1:number):Promise<Array<models.Achievement>>;

export function LoadAchievementsFromSchema(arg1:number):Promise<Array<models.Achievement>>;

export function OpenDataDir():Promise<void>;

export function RescanAllAchievements():Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function ScanAchievementCounts():Promise<void>;

export function SearchGames(arg1:string):Promise<Array<models.GameInfo>>;

export function SetAchievement(arg1:string):Promise<boolean>;

export function SetAllAchievements():Promise<number>;

export function SetToPlay(arg1:number,arg2:boolean):Promise<void>;

export function StopAchievementScan():Promise<void>;

export function StoreStats():Promise<boolean>;
